/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE COMPANION_COMPUTER_PREFLIGHT PACKING
package com.MAVLink.sui_custom;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* Tell the companion computer to perform preflight operations, set the camera, and time
*/
public class msg_companion_computer_preflight extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_COMPANION_COMPUTER_PREFLIGHT = 14;
    public static final int MAVLINK_MSG_LENGTH = 11;
    private static final long serialVersionUID = MAVLINK_MSG_ID_COMPANION_COMPUTER_PREFLIGHT;


      
    /**
    * current time in milliseconds from EPOCH, in UTC
    */
    public long time;
      
    /**
    * camType, a value in the CamType enum in sui-camera
    */
    public short type;
      
    /**
    * System ID
    */
    public short target_system;
      
    /**
    * Component ID
    */
    public short target_component;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_COMPANION_COMPUTER_PREFLIGHT;
              
        packet.payload.putUnsignedLong(time);
              
        packet.payload.putUnsignedByte(type);
              
        packet.payload.putUnsignedByte(target_system);
              
        packet.payload.putUnsignedByte(target_component);
        
        return packet;
    }

    /**
    * Decode a companion_computer_preflight message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.time = payload.getUnsignedLong();
              
        this.type = payload.getUnsignedByte();
              
        this.target_system = payload.getUnsignedByte();
              
        this.target_component = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_companion_computer_preflight(){
        msgid = MAVLINK_MSG_ID_COMPANION_COMPUTER_PREFLIGHT;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_companion_computer_preflight(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_COMPANION_COMPUTER_PREFLIGHT;
        unpack(mavLinkPacket.payload);        
    }

            
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_COMPANION_COMPUTER_PREFLIGHT - sysid:"+sysid+" compid:"+compid+" time:"+time+" type:"+type+" target_system:"+target_system+" target_component:"+target_component+"";
    }
}
        