/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE SET_COMPANION_COMPUTER_CAMTYPE PACKING
package com.MAVLink.sui_custom;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* Select the camera type in the companion computer.
*/
public class msg_set_companion_computer_camtype extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_SET_COMPANION_COMPUTER_CAMTYPE = 14;
    public static final int MAVLINK_MSG_LENGTH = 3;
    private static final long serialVersionUID = MAVLINK_MSG_ID_SET_COMPANION_COMPUTER_CAMTYPE;


      
    /**
    * camType, a value in the CamType enum in sui-camera
    */
    public short type;
      
    /**
    * System ID
    */
    public short target_system;
      
    /**
    * Component ID
    */
    public short target_component;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_SET_COMPANION_COMPUTER_CAMTYPE;
              
        packet.payload.putUnsignedByte(type);
              
        packet.payload.putUnsignedByte(target_system);
              
        packet.payload.putUnsignedByte(target_component);
        
        return packet;
    }

    /**
    * Decode a set_companion_computer_camtype message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.type = payload.getUnsignedByte();
              
        this.target_system = payload.getUnsignedByte();
              
        this.target_component = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_set_companion_computer_camtype(){
        msgid = MAVLINK_MSG_ID_SET_COMPANION_COMPUTER_CAMTYPE;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_set_companion_computer_camtype(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_SET_COMPANION_COMPUTER_CAMTYPE;
        unpack(mavLinkPacket.payload);        
    }

          
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_SET_COMPANION_COMPUTER_CAMTYPE - sysid:"+sysid+" compid:"+compid+" type:"+type+" target_system:"+target_system+" target_component:"+target_component+"";
    }
}
        